server:
  port: ${SQLOJ_PORT:10100}

spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: ${SQLOJ_DB_USER:root}
    password: ${SQLOJ_DB_PASSWORD:sy123456}

mybatis:
#  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: pers.sy.sqloj.entity
